<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class SpawnWP_Deploy_Admin {
	public static function init(): void {
		add_action( 'admin_menu', array( __CLASS__, 'menu' ) );
		add_action( 'admin_init', array( __CLASS__, 'actions' ) );
		add_action( 'wp_ajax_spawnwp_deploy_step', array( __CLASS__, 'ajax_step' ) );
	}

	public static function menu(): void {
		add_management_page( 'SpawnWP Deploy', 'SpawnWP Deploy', 'manage_options', 'spawnwp-deploy', array( __CLASS__, 'page' ) );
	}

	public static function actions(): void {
		if ( ! current_user_can( 'manage_options' ) || empty( $_POST['spawnwp_deploy_action'] ) ) {
			return;
		}
		check_admin_referer( 'spawnwp_deploy_admin' );
		$action = sanitize_key( wp_unslash( $_POST['spawnwp_deploy_action'] ) );
		try {
			if ( 'generate_pairing' === $action ) {
				self::generate_pairing();
			} elseif ( 'connect' === $action ) {
				self::connect( sanitize_textarea_field( wp_unslash( $_POST['pairing_bundle'] ?? '' ) ) );
			} elseif ( 'revoke_local' === $action ) {
				self::revoke_local( sanitize_text_field( wp_unslash( $_POST['connection_id'] ?? '' ) ) );
			} elseif ( 'revoke_target' === $action ) {
				self::revoke_target( sanitize_text_field( wp_unslash( $_POST['connection_id'] ?? '' ) ) );
			} elseif ( 'connect_server' === $action ) {
				SpawnWP_Deploy_Blueprint::connect( sanitize_textarea_field( wp_unslash( $_POST['pairing_bundle'] ?? '' ) ) );
			} elseif ( 'revoke_server' === $action ) {
				SpawnWP_Deploy_Blueprint::revoke( sanitize_text_field( wp_unslash( $_POST['connection_id'] ?? '' ) ) );
			}
			self::redirect( 'success' );
		} catch ( Throwable $error ) {
			self::redirect( rawurlencode( $error->getMessage() ) );
		}
	}

	public static function page(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}
		global $wpdb;
		SpawnWP_Deploy_Database::maintain_connections();
		$message     = isset( $_GET['spawnwp_message'] ) ? sanitize_text_field( wp_unslash( $_GET['spawnwp_message'] ) ) : '';
		$connections = $wpdb->get_results( 'SELECT * FROM ' . SpawnWP_Deploy_Database::table( 'connections' ) . " WHERE role='source' AND status IN ('active','consumed') ORDER BY created_at DESC", ARRAY_A );
		$pending     = $wpdb->get_row( 'SELECT * FROM ' . SpawnWP_Deploy_Database::table( 'connections' ) . " WHERE role='target' AND status='pending' ORDER BY created_at DESC LIMIT 1", ARRAY_A );
		$receivers   = $wpdb->get_results( 'SELECT * FROM ' . SpawnWP_Deploy_Database::table( 'connections' ) . " WHERE role='target' AND status='active' ORDER BY created_at DESC", ARRAY_A );
		$history     = $wpdb->get_results( 'SELECT id,label,role,remote_url,status,updated_at FROM ' . SpawnWP_Deploy_Database::table( 'connections' ) . " WHERE status IN ('expired','revoked') ORDER BY updated_at DESC LIMIT 10", ARRAY_A );
		$guard       = SpawnWP_Deploy_Guard::target_report();
		?>
		<div class="wrap spawnwp-deploy-wrap">
			<h1>Spawn<span>WP</span> Deploy</h1>
			<p class="description">Publish once to a new, empty WordPress site. This is not staging or live synchronization.</p>
			<?php if ( $message ) : ?>
				<div class="notice <?php echo 'success' === $message ? 'notice-success' : 'notice-error'; ?> is-dismissible"><p><?php echo esc_html( 'success' === $message ? 'Action completed.' : rawurldecode( $message ) ); ?></p></div>
			<?php endif; ?>

			<div class="spawnwp-grid">
				<section class="spawnwp-panel">
					<h2>Publish this site</h2>
					<p>Paste the short-lived connection key generated by the empty destination.</p>
					<form method="post">
						<?php wp_nonce_field( 'spawnwp_deploy_admin' ); ?>
						<input type="hidden" name="spawnwp_deploy_action" value="connect">
						<textarea name="pairing_bundle" rows="5" class="large-text code" required placeholder="spawndeploy1:..."></textarea>
						<?php submit_button( 'Connect destination', 'primary', 'submit', false ); ?>
					</form>
				</section>

				<section class="spawnwp-panel">
					<h2>Receive a publication</h2>
					<?php if ( $guard['ok'] ) : ?>
						<p class="spawnwp-ok">Target eligibility: empty and ready.</p>
						<form method="post">
							<?php wp_nonce_field( 'spawnwp_deploy_admin' ); ?>
							<input type="hidden" name="spawnwp_deploy_action" value="generate_pairing">
							<?php submit_button( 'Generate connection key', 'secondary', 'submit', false ); ?>
						</form>
						<?php if ( $pending && strtotime( $pending['pair_expires'] . ' UTC' ) > time() ) : ?>
							<textarea rows="5" class="large-text code" readonly onclick="this.select()"><?php echo esc_textarea( get_transient( 'spawnwp_deploy_bundle_' . $pending['id'] ) ); ?></textarea>
							<p class="description">Expires <?php echo esc_html( gmdate( 'Y-m-d H:i:s', strtotime( $pending['pair_expires'] . ' UTC' ) ) ); ?> UTC.</p>
						<?php endif; ?>
						<?php foreach ( $receivers as $receiver ) : ?>
							<div class="spawnwp-receiver">
								<span>Connected source: <code><?php echo esc_html( $receiver['remote_url'] ); ?></code></span>
								<form method="post">
									<?php wp_nonce_field( 'spawnwp_deploy_admin' ); ?>
									<input type="hidden" name="spawnwp_deploy_action" value="revoke_target">
									<input type="hidden" name="connection_id" value="<?php echo esc_attr( $receiver['id'] ); ?>">
									<button class="button" type="submit">Revoke source</button>
								</form>
							</div>
						<?php endforeach; ?>
					<?php else : ?>
						<p class="spawnwp-bad">Target is not eligible:</p><ul>
						<?php
						foreach ( $guard['issues'] as $issue ) :
							?>
							<li><?php echo esc_html( $issue ); ?></li><?php endforeach; ?>
						</ul>
					<?php endif; ?>
				</section>
			</div>

			<section class="spawnwp-panel spawnwp-connections">
				<h2>Connected destinations</h2>
				<?php
				if ( ! $connections ) :
					?>
					<p>No destination connected.</p><?php endif; ?>
				<?php foreach ( $connections as $connection ) : ?>
					<div class="spawnwp-connection">
						<div><strong><?php echo esc_html( $connection['label'] ?: $connection['remote_url'] ); ?></strong><br><code><?php echo esc_html( $connection['remote_url'] ); ?></code><br><small>Status: <?php echo esc_html( $connection['status'] ); ?></small></div>
						<div class="spawnwp-actions">
							<button class="button button-primary spawnwp-start" data-connection="<?php echo esc_attr( $connection['id'] ); ?>" <?php disabled( 'active' !== $connection['status'] ); ?>>Deploy to empty site</button>
							<?php $last_job = get_option( 'spawnwp_deploy_last_job_' . $connection['id'] ); if ( 'consumed' === $connection['status'] && $last_job ) : ?>
								<button class="button spawnwp-rollback" data-connection="<?php echo esc_attr( $connection['id'] ); ?>" data-job="<?php echo esc_attr( $last_job ); ?>">Rollback</button>
							<?php endif; ?>
							<form method="post">
								<?php wp_nonce_field( 'spawnwp_deploy_admin' ); ?>
								<input type="hidden" name="spawnwp_deploy_action" value="revoke_local"><input type="hidden" name="connection_id" value="<?php echo esc_attr( $connection['id'] ); ?>">
								<button class="button" type="submit">Remove</button>
							</form>
						</div>
					</div>
				<?php endforeach; ?>
				<pre id="spawnwp-log" hidden></pre>
			</section>

			<?php SpawnWP_Deploy_Blueprint::render_panel(); ?>

			<?php if ( $history ) : ?>
				<details class="spawnwp-panel spawnwp-history">
					<summary>Connection history (<?php echo esc_html( count( $history ) ); ?>)</summary>
					<?php foreach ( $history as $item ) : ?>
						<div class="spawnwp-connection">
							<div><strong><?php echo esc_html( $item['label'] ?: ( $item['remote_url'] ?: 'Unused pairing key' ) ); ?></strong><br><small><?php echo esc_html( ucfirst( $item['role'] ) . ' · ' . ucfirst( $item['status'] ) . ' · ' . gmdate( 'Y-m-d H:i:s', strtotime( $item['updated_at'] . ' UTC' ) ) . ' UTC' ); ?></small></div>
						</div>
					<?php endforeach; ?>
					<p class="description">Expired and revoked entries are removed after 30 days when no deployment job references them.</p>
				</details>
			<?php endif; ?>
		</div>
		<style>
		.spawnwp-deploy-wrap h1 span{color:#f6b269}.spawnwp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px;margin:20px 0}.spawnwp-panel{background:#fff;border:1px solid #dcdcde;border-radius:4px;padding:18px;margin:16px 0}.spawnwp-panel h2{margin-top:0}.spawnwp-ok{color:#18743b}.spawnwp-bad{color:#b32d2e;font-weight:600}.spawnwp-connection,.spawnwp-receiver{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 0;border-top:1px solid #dcdcde}.spawnwp-actions{display:flex;gap:8px;align-items:center}.spawnwp-actions form,.spawnwp-receiver form{margin:0}.spawnwp-warning{background:#fcf9e8;border:1px solid #dba617;border-radius:4px;padding:10px 14px;margin:12px 0}.spawnwp-warning ul{margin:6px 0 0 18px;list-style:disc}#spawnwp-log,#spawnwp-bp-log{display:block;background:#0d0d10;color:#f8f8f8;border-left:3px solid #f6b269;padding:14px;max-height:360px;overflow:auto;white-space:pre-wrap}@media(max-width:700px){.spawnwp-connection,.spawnwp-receiver{align-items:flex-start;flex-direction:column}.spawnwp-actions{flex-wrap:wrap}}
		</style>
		<script>
		(function(){
			const ajaxUrl=<?php echo wp_json_encode( admin_url( 'admin-ajax.php' ) ); ?>;
			const nonce=<?php echo wp_json_encode( wp_create_nonce( 'spawnwp_deploy_ajax' ) ); ?>;
			const log=document.getElementById('spawnwp-log');
			function line(text){log.hidden=false;log.textContent+=text+'\n';log.scrollTop=log.scrollHeight;}
			async function step(connection,op,state={}){const body=new URLSearchParams({action:'spawnwp_deploy_step',nonce,connection,op,...state});const response=await fetch(ajaxUrl,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await response.json();if(!data.success)throw new Error(data.data&&data.data.message?data.data.message:'Deployment step failed');return data.data;}
			async function deploy(button){const connection=button.dataset.connection;button.disabled=true;try{line('Checking destination...');let data=await step(connection,'preflight');if(data.warnings&&data.warnings.length){data.warnings.forEach(warning=>line('WARNING: '+warning));if(!confirm(data.warnings.join('\n')+'\n\nContinue anyway?'))throw new Error('Deployment cancelled after compatibility warning.');}line('Destination ready. Building package...');data=await step(connection,'prepare');line('Package ready: '+data.manifest.archive_bytes+' bytes');while(data.next<data.manifest.chunk_count){data=await step(connection,'transfer',{job:data.job,next:String(data.next)});line('Transferred '+data.next+' / '+data.manifest.chunk_count+' chunks');}line('Verifying and staging...');await step(connection,'stage',{job:data.job});if(!confirm('Final confirmation: this will publish the package to the empty destination. Continue?'))throw new Error('Activation cancelled; staged package retained.');line('Activating during a short maintenance window...');const done=await step(connection,'activate',{job:data.job});line('Deployment '+done.state+'.');button.textContent='Deployed';}catch(error){line('ERROR: '+error.message);button.disabled=false;}}
			document.querySelectorAll('.spawnwp-start').forEach(button=>button.addEventListener('click',()=>deploy(button)));
			document.querySelectorAll('.spawnwp-rollback').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Rollback the destination to its pre-deploy state?'))return;button.disabled=true;try{line('Rolling back destination...');const done=await step(button.dataset.connection,'rollback',{job:button.dataset.job});line('Rollback '+done.state+'. Reload this page to deploy again.');}catch(error){line('ERROR: '+error.message);button.disabled=false;}}));
		})();
		</script>
		<?php
	}

	private static function generate_pairing(): void {
		global $wpdb;
		$guard = SpawnWP_Deploy_Guard::target_report();
		if ( ! $guard['ok'] ) {
			throw new RuntimeException( implode( ' ', $guard['issues'] ) );
		}
		$id      = SpawnWP_Deploy_Database::uuid();
		$token   = SpawnWP_Deploy_Crypto::random_token();
		$keys    = SpawnWP_Deploy_Crypto::generate_keypair();
		$expires = gmdate( 'Y-m-d H:i:s', time() + 15 * MINUTE_IN_SECONDS );
		$wpdb->insert(
			SpawnWP_Deploy_Database::table( 'connections' ),
			array(
				'id'              => $id,
				'label'           => 'Pending source',
				'role'            => 'target',
				'remote_url'      => '',
				'public_key'      => '',
				'private_key'     => $keys['private'],
				'owner_user_id'   => get_current_user_id(),
				'pair_token_hash' => hash( 'sha256', $token ),
				'pair_expires'    => $expires,
				'status'          => 'pending',
				'created_at'      => current_time( 'mysql', true ),
				'updated_at'      => current_time( 'mysql', true ),
			)
		);
		$bundle_data = array(
			'version'           => 1,
			'target_url'        => untrailingslashit( home_url() ),
			'pairing_id'        => $id,
			'token'             => $token,
			'target_public_key' => $keys['public'],
			'expires'           => gmdate( 'c', strtotime( $expires . ' UTC' ) ),
		);
		$bundle      = 'spawndeploy1:' . rtrim( strtr( base64_encode( wp_json_encode( $bundle_data ) ), '+/', '-_' ), '=' );
		set_transient( 'spawnwp_deploy_bundle_' . $id, $bundle, 15 * MINUTE_IN_SECONDS );
		SpawnWP_Deploy_Database::audit( 'pairing_key_created', array(), $id );
	}

	private static function connect( string $bundle ): void {
		global $wpdb;
		if ( ! str_starts_with( $bundle, 'spawndeploy1:' ) ) {
			throw new RuntimeException( 'Connection key format is invalid.' );
		}
		$encoded  = substr( $bundle, strlen( 'spawndeploy1:' ) );
		$encoded .= str_repeat( '=', ( 4 - strlen( $encoded ) % 4 ) % 4 );
		$data     = json_decode( base64_decode( strtr( $encoded, '-_', '+/' ), true ), true, 512, JSON_THROW_ON_ERROR );
		if ( empty( $data['target_url'] ) || 'https' !== wp_parse_url( $data['target_url'], PHP_URL_SCHEME ) || strtotime( $data['expires'] ) < time() ) {
			throw new RuntimeException( 'Connection key is expired or does not use HTTPS.' );
		}
		$keys       = SpawnWP_Deploy_Crypto::generate_keypair();
		$secret     = SpawnWP_Deploy_Crypto::decrypt( $keys['private'] );
		$proof_data = 'pair|' . $data['pairing_id'] . '|' . $keys['public'] . '|' . untrailingslashit( home_url() );
		$payload    = array(
			'pairing_id'        => $data['pairing_id'],
			'token'             => $data['token'],
			'source_public_key' => $keys['public'],
			'source_url'        => untrailingslashit( home_url() ),
			'proof'             => base64_encode( sodium_crypto_sign_detached( $proof_data, $secret ) ),
		);
		$response   = wp_remote_post(
			trailingslashit( $data['target_url'] ) . 'wp-json/' . SpawnWP_Deploy_REST::NS . '/pair',
			array(
				'timeout'   => 30,
				'sslverify' => true,
				'headers'   => array( 'Content-Type' => 'application/json' ),
				'body'      => wp_json_encode( $payload ),
			)
		);
		$body       = self::decode_response( $response );
		if ( ! hash_equals( $data['target_public_key'], $body['target_public_key'] ?? '' ) ) {
			throw new RuntimeException( 'Target key confirmation failed.' );
		}
		$wpdb->replace(
			SpawnWP_Deploy_Database::table( 'connections' ),
			array(
				'id'            => $body['connection_id'],
				'label'         => wp_parse_url( $body['target_url'], PHP_URL_HOST ),
				'role'          => 'source',
				'remote_url'    => $body['target_url'],
				'public_key'    => $body['target_public_key'],
				'private_key'   => $keys['private'],
				'owner_user_id' => get_current_user_id(),
				'status'        => 'active',
				'created_at'    => current_time( 'mysql', true ),
				'updated_at'    => current_time( 'mysql', true ),
			)
		);
		SpawnWP_Deploy_Database::audit( 'destination_connected', array( 'target_url' => $body['target_url'] ), $body['connection_id'] );
	}

	public static function ajax_step(): void {
		check_ajax_referer( 'spawnwp_deploy_ajax', 'nonce' );
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( array( 'message' => 'Insufficient permissions.' ), 403 );
		}
		try {
			$connection = self::source_connection( sanitize_text_field( wp_unslash( $_POST['connection'] ?? '' ) ) );
			$op         = sanitize_key( wp_unslash( $_POST['op'] ?? '' ) );
			if ( 'preflight' === $op ) {
				$preflight             = self::remote( $connection, 'GET', '/preflight' );
				$preflight['warnings'] = SpawnWP_Deploy_Guard::compatibility_warnings( SpawnWP_Deploy_Guard::environment(), $preflight['environment'] ?? array() );
				wp_send_json_success( $preflight );
			}
			if ( 'prepare' === $op ) {
				$preflight = self::remote( $connection, 'GET', '/preflight' );
				if ( empty( $preflight['ok'] ) ) {
					throw new RuntimeException( implode( ' ', $preflight['issues'] ?? array( 'Target preflight failed.' ) ) );
				}
				$local    = SpawnWP_Deploy_Database::uuid();
				$manifest = SpawnWP_Deploy_Package::prepare( $local, $connection['remote_url'], $preflight['environment'] );
				$remote   = self::remote( $connection, 'POST', '/jobs', wp_json_encode( $manifest ) );
				$state    = array(
					'local'    => $local,
					'job'      => $remote['job_id'],
					'manifest' => $manifest,
					'next'     => 0,
				);
				update_option( 'spawnwp_deploy_source_job_' . $remote['job_id'], $state, false );
				update_option( 'spawnwp_deploy_last_job_' . $connection['id'], $remote['job_id'], false );
				wp_send_json_success( $state );
			}
			$job_id = sanitize_text_field( wp_unslash( $_POST['job'] ?? '' ) );
			$state  = get_option( 'spawnwp_deploy_source_job_' . $job_id );
			if ( ! is_array( $state ) || $state['job'] !== $job_id ) {
				throw new RuntimeException( 'Source deployment state was not found.' );
			}
			if ( 'transfer' === $op ) {
				$index = isset( $_POST['next'] ) ? absint( wp_unslash( $_POST['next'] ) ) : (int) $state['next'];
				$chunk = SpawnWP_Deploy_Package::chunk( $state['local'], $index, (int) $state['manifest']['chunk_size'] );
				self::remote(
					$connection,
					'PUT',
					'/jobs/' . rawurlencode( $job_id ) . '/chunks/' . $index,
					$chunk,
					array(
						'X-SpawnWP-Chunk-SHA256' => hash( 'sha256', $chunk ),
						'Content-Type'           => 'application/octet-stream',
					)
				);
				$state['next'] = $index + 1;
				update_option( 'spawnwp_deploy_source_job_' . $job_id, $state, false );
				wp_send_json_success( $state );
			}
			if ( 'stage' === $op ) {
				wp_send_json_success( self::remote( $connection, 'POST', '/jobs/' . rawurlencode( $job_id ) . '/stage', '{}' ) );
			}
			if ( 'activate' === $op ) {
				$result = self::remote( $connection, 'POST', '/jobs/' . rawurlencode( $job_id ) . '/activate', '{}' );
				self::mark_connection( $connection['id'], 'consumed' );
				SpawnWP_Deploy_Package::cleanup( $state['local'] );
				wp_send_json_success( $result );
			}
			if ( 'rollback' === $op ) {
				$result = self::remote( $connection, 'POST', '/jobs/' . rawurlencode( $job_id ) . '/rollback', '{}' );
				self::mark_connection( $connection['id'], 'active' );
				wp_send_json_success( $result );
			}
			throw new RuntimeException( 'Unknown deployment operation.' );
		} catch ( Throwable $error ) {
			wp_send_json_error( array( 'message' => $error->getMessage() ), 409 );
		}
	}

	private static function remote( array $connection, string $method, string $route, string $body = '', array $extra_headers = array() ): array {
		$path      = '/' . SpawnWP_Deploy_REST::NS . $route;
		$timestamp = time();
		$nonce     = SpawnWP_Deploy_Crypto::random_token( 18 );
		$headers   = array_merge(
			array(
				'Content-Type'         => 'application/json',
				'X-SpawnWP-Connection' => $connection['id'],
				'X-SpawnWP-Timestamp'  => (string) $timestamp,
				'X-SpawnWP-Nonce'      => $nonce,
				'X-SpawnWP-Signature'  => SpawnWP_Deploy_Crypto::sign( $connection['private_key'], $method, $path, $timestamp, $nonce, $body ),
			),
			$extra_headers
		);
		$response  = wp_remote_request(
			trailingslashit( $connection['remote_url'] ) . 'wp-json' . $path,
			array(
				'method'      => $method,
				'timeout'     => 120,
				'sslverify'   => true,
				'redirection' => 0,
				'headers'     => $headers,
				'body'        => $body,
				'data_format' => 'body',
			)
		);
		return self::decode_response( $response );
	}

	private static function decode_response( $response ): array {
		if ( is_wp_error( $response ) ) {
			throw new RuntimeException( $response->get_error_message() );
		}
		$status = wp_remote_retrieve_response_code( $response );
		$data   = json_decode( wp_remote_retrieve_body( $response ), true );
		if ( $status < 200 || $status >= 300 ) {
			throw new RuntimeException( $data['message'] ?? 'Remote request failed with HTTP ' . $status );
		}
		return is_array( $data ) ? $data : array();
	}

	private static function source_connection( string $id ): array {
		global $wpdb;
		$row = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . SpawnWP_Deploy_Database::table( 'connections' ) . " WHERE id=%s AND role='source' AND status IN ('active','consumed')", $id ), ARRAY_A );
		if ( ! $row ) {
			throw new RuntimeException( 'Active destination connection not found.' );
		}
		return $row;
	}

	private static function revoke_local( string $id ): void {
		global $wpdb;
		$connection = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . SpawnWP_Deploy_Database::table( 'connections' ) . " WHERE id=%s AND role='source'", $id ), ARRAY_A );
		if ( ! $connection ) {
			throw new RuntimeException( 'Source connection not found.' );
		}
		if ( in_array( $connection['status'], array( 'active', 'consumed' ), true ) ) {
			try {
				self::remote( $connection, 'DELETE', '/connection' );
			} catch ( Throwable $error ) {
				SpawnWP_Deploy_Database::audit( 'remote_revoke_unreachable', array( 'error' => $error->getMessage() ), $id );
			}
		}
		$wpdb->update(
			SpawnWP_Deploy_Database::table( 'connections' ),
			array( 'status' => 'revoked', 'private_key' => '', 'updated_at' => current_time( 'mysql', true ) ),
			array( 'id' => $id )
		);
	}

	private static function revoke_target( string $id ): void {
		global $wpdb;
		$wpdb->update(
			SpawnWP_Deploy_Database::table( 'connections' ),
			array( 'status' => 'revoked', 'private_key' => '', 'updated_at' => current_time( 'mysql', true ) ),
			array( 'id' => $id, 'role' => 'target' )
		);
		SpawnWP_Deploy_Database::audit( 'connection_revoked_locally', array(), $id );
	}

	private static function mark_connection( string $id, string $status ): void {
		global $wpdb;
		$wpdb->update(
			SpawnWP_Deploy_Database::table( 'connections' ),
			array(
				'status'     => $status,
				'updated_at' => current_time( 'mysql', true ),
			),
			array( 'id' => $id )
		);
	}

	private static function redirect( string $message ): void {
		wp_safe_redirect(
			add_query_arg(
				array(
					'page'            => 'spawnwp-deploy',
					'spawnwp_message' => $message,
				),
				admin_url( 'tools.php' )
			)
		);
		exit;
	}
}
